{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bankapp.fullname" . }}-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bankapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    app: {{ include "bankapp.fullname" . }}-mysql

{{- end }}

{{- if .Values.ollama.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bankapp.fullname" . }}-ollama
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bankapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 11434
      targetPort: 11434
      protocol: TCP
      name: ollama
  selector:
    app: {{ include "bankapp.fullname" . }}-ollama

{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bankapp.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bankapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.bankapp.service.type }}
  sessionAffinity: ClientIP
  ports:
    - port: {{ .Values.bankapp.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ include "bankapp.fullname" . }}
